-- Kill icons for MW2 killstreak entities
killicon.Add( "sent_predator_missile", "vgui/killicons/predator_missile",    Color( 255, 255, 255 ) )
killicon.Add( "sent_air_strike_bomb",  "vgui/killicons/precision_air_strike", Color( 255, 255, 255 ) )
killicon.Add( "sent_harrier",          "vgui/killicons/harrier",              Color( 255, 255, 255 ) )
killicon.Add( "sent_ac-130",           "vgui/killicons/ac-130",               Color( 255, 255, 255 ) )
killicon.Add( "mw2_sentrygun",         "vgui/killicons/sentry_gun",           Color( 255, 255, 255 ) )
killicon.Add( "sent_supplycrate",      "vgui/killicons/supply_crate",         Color( 255, 255, 255 ) )
killicon.Add( "worldspawn",            "vgui/killicons/world",                Color( 255, 255, 255 ) )
killicon.AddAlias( "sent_105mm",  "sent_ac-130" )
killicon.AddAlias( "sent_40mm",   "sent_ac-130" )
killicon.AddAlias( "sent_bomblet", "sent_air_strike_bomb" )
